server:
  port: 9000
spring:
  kafka:
    consumer:
      bootstrap-servers:  ${bootstrap_servers}
      group-id: ${sink_consumer_group}
      topic: ${sink_consumer_topic}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: ${bootstrap_servers}
      topic: ${sink_producer_topic}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
