global:
  scrape_interval: 5s
  evaluation_interval: 5s
              
scrape_configs:
  - job_name: 'kubernetes-apiservers'    
    kubernetes_sd_configs:
      - role: endpoints        
                    
  - job_name: 'kubernetes-nodes'      
    kubernetes_sd_configs:
      - role: node
                
  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod
      
  - job_name: 'kube-state-metrics'
    static_configs:
      - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']
            
  - job_name: 'kubernetes-cadvisor'                    
    kubernetes_sd_configs:
      - role: node
      
  - job_name: 'kubernetes-service-endpoints'
    kubernetes_sd_configs:
      - role: endpoints

  - job_name: 'otel-collector'
    scrape_interval: 10s
    static_configs:
      - targets: ['otel-collector.otel:8888','otel-collector.otel:8889']

