version: '3.7'
services:
  swir-example-configurator:
    networks:
      - swir-net
    image: swir/swir-example-pubsub-configurator:v0.4.0
    command: ["/bin/bash","-c","cp /config/* swir_config/"]
    volumes:
      - type: volume
        source: swir_config
        target: /swir_config


  prometheus:
    networks:
      - swir-net
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
        
  jaeger-all-in-one:
    networks:
      - swir-net
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

      

  otel-collector:
    networks:
      - swir-net
    image: otel/opentelemetry-collector-dev:latest
    command: ["--config=/etc/otel-collector-config.yaml", "${OTELCOL_ARGS}"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317"        # OTLP gRPC receiver
      - "55670:55679" # zpages extension
    depends_on:
      - jaeger-all-in-one

  # Agent
  otel-agent:
    networks:
      - swir-net
    image: otel/opentelemetry-collector-dev:latest
    command: ["--config=/etc/otel-agent-config.yaml", "${OTELCOL_ARGS}"]
    volumes:
      - ./otel-agent-config.yaml:/etc/otel-agent-config.yaml
    ports:
      - "8887:8888"   # Prometheus metrics exposed by the agent
      - "14250"       # Jaeger grpc receiver
      - "14268"       # Jaeger http thrift receiver
      - "55678"       # OpenCensus receiver
      - "4317"        # OTLP gRPC receiver
      - "9411"        # Zipkin receiver
      - "1777:1777"   # pprof extension
      - "55679:55679" # zpages extension
      - "13133"       # health_check
    depends_on:
      - otel-collector
      

# step 1 
# Java gRCP
  order-generator-sidecar:
    networks:
      - swir-net
    image: swir/swir:v0.4.0
    depends_on:
      - swir-example-configurator
      - otel-agent
    ports:
      - "8080"
      - "8443"
      - "50051"
    environment:
      - swir_config_file=/swir_config/swir_source.yaml
    volumes:
      - type: volume
        source: swir_config
        target: /swir_config

# step 2     
# python gRPC
  order-processor-sidecar:
    networks:
      - swir-net
    image: swir/swir:v0.4.0
    depends_on:
      - swir-example-configurator
      - otel-agent
    ports:
      - "8080"
      - "8443"
      - "50051"
    environment:
      - swir_config_file=/swir_config/swir_processor_1.yaml
    volumes:
      - type: volume
        source: swir_config
        target: /swir_config

# step 3           
# Java SpringBoot and REST        
  inventory-processor-sidecar:
    networks:
      - swir-net
    image: swir/swir:v0.4.0
    depends_on:
      - swir-example-configurator
      - otel-agent
    ports:
      - "8080"
      - "8443"
      - "50051"
    environment:
      - swir_config_file=/swir_config/swir_processor_2.yaml
    volumes:
      - type: volume
        source: swir_config
        target: /swir_config


# step 4           
# python gRPC              
  billing-processor-sidecar:
    networks:
      - swir-net
    image: swir/swir:v0.4.0
    depends_on:
      - swir-example-configurator
      - otel-agent
    ports:
      - "8080"
      - "8443"
      - "50051"
    environment:
      - swir_config_file=/swir_config/swir_processor_3.yaml

    volumes:
      - type: volume
        source: swir_config
        target: /swir_config


# step 5
# Python gRPC
  shipments-sink-sidecar:
    networks:
      - swir-net
    image: swir/swir:v0.4.0
    depends_on:
      - swir-example-configurator
      - otel-agent
    ports:
      - "8080"
      - "8443"
      - "50051"
    environment:
      - swir_config_file=/swir_config/swir_sink.yaml

    volumes:
      - type: volume
        source: swir_config
        target: /swir_config                
  
# step 1 
# Java gRCP
  order-generator:
    networks:
      - swir-net
    image: swir/swir-example-pubsub-java-source:v0.4.0
    depends_on:
      - order-generator-sidecar
    environment:
      - sidecar_hostname=order-generator-sidecar
      - sidecar_port=50051
      - produce_topic=orders
      - client_database_name=source_store
        

# step 2     
# python gRPC
  order-processor:
    networks:
      - swir-net
    image: swir/swir-example-pubsub-python-processor:v0.4.0
    depends_on:
      - order-processor-sidecar
    environment:
      - sidecar=order-processor-sidecar:50051
      - subscribe_topic=orders
      - publish_topic=inventory


# step 3           
# Java SpringBoot and REST
  inventory-processor:
    networks:
      - swir-net
    image: swir/swir-example-pubsub-java-processor:v0.4.0
    depends_on:
      - inventory-processor-sidecar
    ports:
      - "8080"
    environment:
      - sidecar_url=http://inventory-processor-sidecar:8080
      - subscribe_topic=inventory
      - producer_topic=billing
      - server_port=8080

# step 4           
# python gRPC      
  billing-processor:
    networks:
      - swir-net
    image: swir/swir-example-pubsub-python-processor:v0.4.0
    depends_on:
      - billing-processor-sidecar
    environment:
      - sidecar=billing-processor-sidecar:50051
      - subscribe_topic=billing
      - publish_topic=shipments

# step 5
# Python gRPC
  shipments-sink:
    networks:
      - swir-net
    image: swir/swir-example-pubsub-python-sink:v0.4.0
    depends_on:
      - shipments-sink-sidecar
    environment:
      - sidecar=shipments-sink-sidecar:50051
      - subscribe_topic=shipments
      - client_database_name=sink_store


volumes:
  swir_config:
networks:
  swir-net:
    external:
      name: docker_swir-net

