version: '3.7'
# Sidecars layer. All sidecars are already deployed.
services:
  swir-example-si-configurator:
    networks:
      - swir-si
    image: swir/swir-example-si-configurator:v0.4.0
#    command: ["/bin/bash","-c","cp /config/* swir_config/ ; cp /certificates/* certs/"]
    volumes:
      - type: volume
        source: swir_config
        target: /swir_config
      - type: volume
        source: certs
        target: /certs
        
  prometheus:
    networks:
      - swir-si
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
        
  jaeger-all-in-one:
    networks:
      - swir-si
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

      

  otel-collector:
    networks:
      - swir-si
    image: otel/opentelemetry-collector-dev:latest
    command: ["--config=/etc/otel-collector-config.yaml", "${OTELCOL_ARGS}"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317"        # OTLP gRPC receiver
      - "55670:55679" # zpages extension
    depends_on:
      - jaeger-all-in-one

  # Agent
  otel-agent:
    networks:
      - swir-si
    image: otel/opentelemetry-collector-dev:latest
    command: ["--config=/etc/otel-agent-config.yaml", "${OTELCOL_ARGS}"]
    volumes:
      - ./otel-agent-config.yaml:/etc/otel-agent-config.yaml
    ports:
      - "8887:8888"   # Prometheus metrics exposed by the agent
      - "14250"       # Jaeger grpc receiver
      - "14268"       # Jaeger http thrift receiver
      - "55678"       # OpenCensus receiver
      - "4317"        # OTLP gRPC receiver
      - "9411"        # Zipkin receiver
      - "1777:1777"   # pprof extension
      - "55679:55679" # zpages extension
      - "13133"       # health_check
    depends_on:
      - otel-collector
      
                  

  orchestator_sidecar:
    networks:
      - swir-si
    image: swir/swir:v0.4.0
    depends_on:
      - swir-example-si-configurator
      - otel-agent
    ports:
      - "8080"
      - "8443"
      - "50051"
      - "50052"
    environment:
      - swir_config_file=/swir_config/swir_source.yaml
    volumes:
      - type: volume
        source: swir_config
        target: /swir_config
      - type: volume
        source: certs
        target: /certs                



  books_sidecar:
    networks:
      - swir-si
    image: swir/swir:v0.4.0
    depends_on:
      - swir-example-si-configurator
      - otel-agent      
    ports:
      - "8080"
      - "8443"
      - "50051"
      - "50052"
    environment:
      - swir_config_file=/swir_config/swir_books_service.yaml
    volumes:
      - type: volume
        source: swir_config
        target: /swir_config
      - type: volume
        source: certs
        target: /certs        


  magazinges_sidecar:
    networks:
      - swir-si
    image: swir/swir:v0.4.0
    depends_on:
      - swir-example-si-configurator
      - otel-agent      
    ports:
      - "8080"
      - "8443"
      - "50051"
      - "50052"
    environment:
      - swir_config_file=/swir_config/swir_magazine_service.yaml
    volumes:
      - type: volume
        source: swir_config
        target: /swir_config
      - type: volume
        source: certs
        target: /certs

  books:
    networks:
      - swir-si
    image: swir/swir-example-si-python-http-server:v0.4.0
    depends_on:
     - books_sidecar
    environment:
      - port=8090
      - ip=0.0.0.0

  magazines:
    networks:
      - swir-si
    image: swir/swir-example-si-python-http-server:v0.4.0
    depends_on:
      - magazinges_sidecar
    environment:
      - ip=0.0.0.0
      - port=8090

  orchestrator_app:
    networks:
      - swir-si
    image: swir/swir-example-si-python-grpc-client:v0.4.0
    depends_on:
     - orchestator_sidecar
    environment:
      - sidecar=orchestator_sidecar:50051
      - service_names=books,magazines

        
volumes:
  swir_config:
  certs:
networks:
  swir-si:

