version: '3.7'
services:

  prometheus:
    networks:
      - swir-net
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
        
  jaeger-all-in-one:
    networks:
      - swir-net
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

      
  otel-collector:
    networks:
      - swir-net
    image: otel/opentelemetry-collector-dev:latest
    command: ["--config=/etc/otel-collector-config.yaml", "${OTELCOL_ARGS}"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317"        # OTLP gRPC receiver
      - "55670:55679" # zpages extension
    depends_on:
      - jaeger-all-in-one

  # Agent
  otel-agent:
    networks:
      - swir-net
    image: otel/opentelemetry-collector-dev:latest
    command: ["--config=/etc/otel-agent-config.yaml", "${OTELCOL_ARGS}"]
    volumes:
      - ./otel-agent-config.yaml:/etc/otel-agent-config.yaml
    ports:
      - "8887:8888"   # Prometheus metrics exposed by the agent
      - "14250"       # Jaeger grpc receiver
      - "14268"       # Jaeger http thrift receiver
      - "55678"       # OpenCensus receiver
      - "4317:4317"        # OTLP gRPC receiver
      - "9411"        # Zipkin receiver
      - "1777:1777"   # pprof extension
      - "55679:55679" # zpages extension
      - "13133"       # health_check
    depends_on:
      - otel-collector
  
  
    
  swir-kafka-sink1:
    networks:
      - swir-net
    image: swir/swir-perf-kafka-sink:v0.4.0
    environment:
      - bootstrap_servers=kafka:9094
      - sink_consumer_topic=Request
      - sink_consumer_group=swir
      - sink_producer_topic=Response
        
  swir-kafka-sink2:
    networks:
      - swir-net
    image: swir/swir-perf-kafka-sink:v0.4.0
    environment:
      - bootstrap_servers=kafka:9094
      - sink_consumer_topic=Request2
      - sink_consumer_group=swir
      - sink_producer_topic=Response2
  


      
  swir-nats-sink:
    networks:
      - swir-net
    image: swir/swir-perf-nats-sink:v0.4.0
    environment:
      - bootstrap_servers=nats://nats:4222
      - subscribe_topic=Request
      - response_topic=Response
        
  swir-nats-sink2:
    networks:
      - swir-net
    image: swir/swir-perf-nats-sink:v0.4.0
    environment:
      - bootstrap_servers=nats://nats:4222
      - subscribe_topic=Request2
      - response_topic=Response2
  
     
  swir-java-client:
    networks:
      - swir-net
    image: swir/swir-perf-java-client:v0.4.0
    environment:
      - sidecar_url=h2://swir:8080/publish
      - bootstrap_servers=kafka:9094
      - consumer_topic=ResponseNoSidecar
      - consumer_group=swir
      - producer_topic=RequestNoSidecar

  redis:
    networks:
      - swir-net
    image: redis
    ports:
      - "6379:6379"

      
networks:
  swir-net:
    external:
      name: docker_swir-net
