receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

  
exporters:
  logging:
    loglevel: debug
  prometheus:
    endpoint: 0.0.0.0:8889
    namespace: agent
    const_labels:
      collector: pf
      type: docker
  jaeger:
    endpoint: jaeger-all-in-one:14250
    insecure: true

processors:
  batch:

extensions:
  pprof:
    endpoint: :1777
  zpages:
    endpoint: :55679
  health_check:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger,logging]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus,logging]
