receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4318

  
exporters:
  otlp:
    endpoint: "otel-collector:4317"
    insecure: true
  logging:
    loglevel: debug
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: agent
    const_labels:
      collector: pf
      type: docker

processors:
  batch:

extensions:
  pprof:
    endpoint: :1777
  zpages:
    endpoint: :55679
  health_check:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp,logging]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp,prometheus,logging]
