server:
  port: 9000
spring:
  cloud:
    stream:
      bindings:
        input1:
          destination: Request
          binder: nats
        output1:
          destination: Response
          binder: nats
        input2:
          destination: Request2
          binder: nats
        output2:
          destination: Response2
          binder: nats
nats:
  spring:
    server: ${bootstrap_servers}


