receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
  
exporters:
  logging:
    loglevel: debug
    
  otlp:
    endpoint: "otel-collector.otel.monitoring:4317"
    insecure: true
  
processors:
  batch:

extensions:
  pprof:
    endpoint: :1777
  zpages:
    endpoint: :55679
  health_check:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
